export source_db_user="postgres"
export source_db_password=""
export source_db_server_name="localhost"
export source_db_database_name="project-one"
export target_db_user="postgres"
export target_db_password=""
export target_db_server_name="localhost"
export target_db_database_name="project-one"
