set source_db_user=postgres
set source_db_password=postgres
set source_db_server_name=localhost
set source_db_database_name=crypto
set target_db_user=postgres
set target_db_password=postgres
set target_db_server_name=localhost
set target_db_database_name=crypto_2